import sys
import os
import uuid
import json
import asyncio
from unittest.mock import AsyncMock

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Monkey-patch config before importing 
from app.core.config import settings
from qdrant_client import QdrantClient
from qdrant_client.http import models

# Patch Qdrant to be in-memory for the test before loading services
import app.db.qdrant as qdrant_mod
qdrant_mod.qdrant_client = QdrantClient(":memory:")

from app.services.chat_engine import ChatEngine
from app.services.retrieval import RetrievalService
from app.services.vector_store import VectorStoreService

async def main():
    project_id = uuid.uuid4()
    doc1_id = uuid.uuid4()
    doc2_id = uuid.uuid4()
    user_id = uuid.uuid4()
    session_id = uuid.uuid4()
    
    # 1. Setup Document Boundaries
    text1 = "Study A (2025) concluded that high dietary sodium is completely unrelated to cardiovascular risk in modern adults, suggesting salt intake can be unmoderated."
    text2 = "Study B (2026) contradicted earlier findings, asserting that high dietary sodium is definitively the leading factor accelerating cardiovascular risk in urban adults."
    
    # Initialize Memory Collection
    qdrant_mod.ensure_collection() # Should bypass seamlessly or we explicitly create
    try:
        qdrant_mod.qdrant_client.create_collection(
            collection_name="document_chunks",
            vectors_config=models.VectorParams(size=384, distance=models.Distance.COSINE),
            on_disk_payload=False
        )
    except:
        pass
    
    retrieval_svc = RetrievalService()
    vs = VectorStoreService()
    
    print("\n[*] Generating Embeddings natively via mapped cross-encoders/embedders...")
    # Generate actual embeddings using the pipeline's sentence-transformers mapping
    embs = retrieval_svc.embedding_service.generate_embeddings([text1, text2])
    
    # Let's recreate properly matching actual dimension array sizing
    dim_size = len(embs[0])
    qdrant_mod.qdrant_client.recreate_collection(
        collection_name="document_chunks",
        vectors_config=models.VectorParams(size=dim_size, distance=models.Distance.COSINE),
    )
    
    chunks = [
        {"vector": embs[0], "payload": {"project_id": str(project_id), "pdf_id": str(doc1_id), "page_number": 1, "chunk_index": 0, "text": text1, "filename": "Study_A_Sodium.pdf", "type": "chunk"}},
        {"vector": embs[1], "payload": {"project_id": str(project_id), "pdf_id": str(doc2_id), "page_number": 2, "chunk_index": 0, "text": text2, "filename": "Study_B_Sodium.pdf", "type": "chunk"}}
    ]
    
    print("\n[*] Indexing fully mapped documents into Local Execution Qdrant Memory...")
    vs.upsert_chunks(chunks)
    
    # Ensure it's searchable
    await asyncio.sleep(1)
    
    # 2. Setup Chat Engine
    mock_chat_svc = AsyncMock()
    class DummySession:
        def __init__(self, pid):
            self.project_id = pid
    mock_chat_svc.get_session_details.return_value = (DummySession(project_id), [])
    
    engine = ChatEngine(chat_service=mock_chat_svc)
    
    # 3. Simulate The User Query
    message = "Compare the conclusions regarding the impact of dietary sodium across these papers."
    print(f"\nUser Request: {message}")
    
    print("\n--- LLM Final Generation Stream ---")
    generator = engine.stream_chat(
        user_id=user_id,
        session_id=session_id,
        project_id=project_id,
        message=message,
        pdf_ids=[str(doc1_id), str(doc2_id)]  # ensure they are strings when passed!
    )
    
    final_text = ""
    f_log = open("generator_debug.txt", "w")
    async for chunk in generator:
        f_log.write(f"RAW CHUNK: {repr(chunk)}\n")
        f_log.flush()
        if chunk.startswith("data: "):
             try:
                 # Be careful since there might be \n\n on the end
                 clean_json = chunk.replace("data: ", "", 1).strip()
                 obj = json.loads(clean_json)
                 
                 f_log.write(f"PARSED JSON: {obj}\n")
                 
                 if obj.get('type') == 'token':
                     # print(obj['content'], end='', flush=True)  # Already printing raw
                     final_text += obj['content']
                 elif obj.get('type') == 'verification':
                     pass
                 elif obj.get('type') == 'error':
                     final_text += "ERROR: " + obj.get('content', '')
             except Exception as e:
                 f_log.write(f"FAILED TO PARSE JSON! err: {e}\n")
                 print(f"FAILED TO PARSE JSON! chunk: {repr(chunk)} err: {e}")
                 
    f_log.close()
    print("\n-----------------------------------\n")
    
    print("\n[*] Validating Cross-Document Citations natively generated by Gemini bounds...")
    
    with open("e2e_test_output.txt", "w") as f:
        f.write(final_text)
        
    print(f"\n--- Final Answer Generated ---\n{final_text}\n------------------------------")
    
    assert "Study_A_Sodium.pdf" in final_text or "Study A" in final_text, f"Missing citation from Document A. Generated text: {final_text}"
    assert "Study_B_Sodium.pdf" in final_text or "Study B" in final_text, f"Missing citation from Document B. Generated text: {final_text}"
    
    print("\n✅ Verification COMPLETE: Both documents evaluated and naturally compared seamlessly via balancing logic!\n")

if __name__ == "__main__":
    asyncio.run(main())
